# .goreleaser.yml
# Build customization

builds:
  - binary: trident-client
    id: "client"
    main: ./client/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - binary: trident-server
    id: "server"
    main: ./server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format_overrides:
      - goos: windows
        format: zip
  files:
    - .client.json
    - .server.json
    - trident-client.service
    - trident-server.service
    - supervisord.conf
    - whiteiplist.pac
    - start.sh
